{% set name = "large-image-viewer" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Large-Image-Viewer-{{ version }}.tar.gz
  sha256: 507baf46c9e13cfea7e2ba72cdfa85349c6db2becd036b4afdea27e02fab0c92

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42.0.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - numpy
    - dask-core
    - dask-image
    - scikit-image

test:
  imports:
    - large_image_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/Large-Image-Viewer
  summary: A simple plugin to view large images
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
